climate:
  - platform: generic_thermostat
    name: Living Room
    heater: switch.living_room_heater_output
    target_sensor: sensor.living_room_average_temperature
    min_temp: 10
    max_temp: 30
    target_temp: 20
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 150
    keep_alive:
      minutes: 3
    away_temp: 14
    precision: 0.1

  - platform: generic_thermostat
    name: Bedroom
    heater: switch.bedroom_heater_output
    target_sensor: sensor.bedroom_average_temperature
    min_temp: 10
    max_temp: 30
    target_temp: 16
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 3
    away_temp: 14
    precision: 0.1

light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.hue_ambiance_spot_1
      - light.hue_ambiance_spot_2
      - light.hue_white_spot_1
      - light.hue_white_spot_2
      - light.hue_color_lamp_1
      - light.hue_ambiance_candle_1

  - platform: group
    name: Bedroom Lights
    entities:
      - light.hue_ambiance_spot_1_2
      - light.hue_ambiance_spot_2_2
      - light.hue_white_lamp_1
      - light.hue_ambiance_candle_2


sensor:
  - platform: min_max
    name: “Living Room Average Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.living_room_pithy_screen_temperature
      - sensor.living_room_pithy_pixel_temperature

  - platform: min_max
    name: “Bedroom Average Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.bedroom_pithy_screen_temperature
      - sensor.bedroom_pithy_pixel_temperature

  - platform: template
    sensors:
      living_room_climate_setpoint:
        friendly_name: 'Living Room Climate Setpoint'
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.living_room', 'temperature') | round(0) }}"

  - platform: template
    sensors:
      bedroom_climate_setpoint:
        friendly_name: 'Bedroom Climate Setpoint'
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.bedroom', 'temperature') | round(0) }}"

  - platform: template
    sensors:
      living_room_lights_warmth:
        friendly_name: 'Living Room Lights Warmth'
        value_template: "{{ state_attr('light.living_room_lights', 'color_temp') | round(0) }}"

  - platform: template
    sensors:
      living_room_lights_brightness:
        friendly_name: 'Living Room Lights Brightness'
        value_template: "{{ state_attr('light.living_room_lights', 'brightness') | round(0) }}"

  - platform: template
    sensors:
      bedroom_lights_warmth:
        friendly_name: 'Bedroom Lights Warmth'
        value_template: "{{ state_attr('light.bedroom_lights', 'color_temp') | round(0) }}"

  - platform: template
    sensors:
      bedroom_lights_brightness:
        friendly_name: 'Bedroom Lights Brightness'
        value_template: "{{ state_attr('light.bedroom_lights', 'brightness') | round(0) }}"

  - platform: template
    sensors:
      living_room_sonos_volume:
        friendly_name: 'Living Room Sonos Volume'
        value_template: "{{ state_attr('media_player.living_room_sonos', 'volume_level') * 100 | round(0) }}"

  - platform: template
    sensors:
      bedroom_sonos_volume:
        friendly_name: 'Bedroom Sonos Volume'
        value_template: "{{ state_attr('media_player.bedroom_sonos', 'volume_level') * 100 | round(0) }}"