climate:
  - platform: generic_thermostat
    name: Demo Climate
    heater: switch.demo_heater_output
    target_sensor: sensor.demo_average_temperature
    min_temp: 10
    max_temp: 30
    target_temp: 16
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 3
    away_temp: 10
    precision: 0.1

sensor:
  - platform: min_max
    name: “Demo Average Temperature"
    type: mean #AVERAGES ALL AVAILABLE VALUES
    round_digits: 1
    entity_ids:
      - sensor.counter_wedge_plus_temperature
      - sensor.plug_neopixel_temperature
      - sensor.plug_screen_temperature
  
  - platform: min_max
    name: “Demo Average Humidity"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.counter_wedge_plus_humidity
      - sensor.plug_neopixel_humidity
      - sensor.plug_screen_humidity

  - platform: template
    sensors: 
      demo_climate_setpoint:
        friendly_name: 'Demo Climate Setpoint' 
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.demo_climate', 'temperature') | round(0) }}"
