substitutions:
  boardPlatform: ESP8266
  boardName: d1_mini
  
  devicename: living_room_pithy_screen
  deviceUpper: Living Room Screen
  deviceParent: living_room

  encoderPinA: D5
  encoderPinB: D6
  encoderSwitch: D7
  i2cData: D4
  i2cClock: D3
###############################################
esphome:
  name: $devicename
  platform: $boardPlatform
  board: $boardName

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

captive_portal:
logger:
ota:
  password: !secret ota_pass
  
i2c:
  sda: ${i2cData}
  scl: ${i2cClock}
  scan: True
  id: bus_a

api:
  password: !secret api_pass

font:
  - file: "fonts/SFCompactText.ttf"
    id: small_font
    size: 18
    glyphs: ":/&!°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz ."

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    update_interval: 1s
    id: i2cDisplay
    pages:
      - id: pageMain
        lambda: |-
          id(menu_tracker).publish_state(0);
          
      - id: pageBrightness
        lambda: |-
          id(menu_tracker).publish_state(1);
          
          it.rectangle(13, 0, 102, 16);
          it.filled_rectangle(14, 1, id(brightness_percent).state, 14);
          it.printf(17, 39, id(small_font), "Brightness");
      - id: pageWarmth
        lambda: |-
          id(menu_tracker).publish_state(2);
          
          it.rectangle(13, 0, 102, 16);
          it.filled_rectangle(14, 1, id(warmth_percent).state, 14);
          it.printf(32, 39, id(small_font), "Warmth");

switch:
  - platform: restart
    name: "ESP Restart ${deviceUpper}"
    
sensor:
  - platform: wifi_signal
    name: ESP Signal ${deviceUpper}
    update_interval: 60s

  - platform: uptime
    name: ESP Uptime ${deviceUpper}
    update_interval: 60s
    
  - platform: sht3xd
    temperature:
      name: "${deviceUpper} Temperature"
      id: ${devicename}_temperature
    humidity:
      name: "${deviceUpper} Humidity"
      id: ${devicename}_humidity
    address: 0x44
    update_interval: 15s
    
  - platform: rotary_encoder
    id: rotary_dial
    pin_a:
      number: ${encoderPinA}
      inverted: true
      mode: INPUT_PULLUP
    pin_b:
      number: ${encoderPinB}
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - debounce: 0.3s
      - lambda: |-
          if(id(menu_tracker).state == 1) {
            if (x < 0.0) return 0.0;
            if (x > 254.0) return 254.0;
            return x;
          } else if(id(menu_tracker).state == 2) {
            if (x < 153.0) return 153.0;
            if (x > 465.0) return 465.0;
            return x;
          } else {
            return x;
          }
    resolution: 4
    min_value: 0
    max_value: 465
    on_value: 
      then:
        - if:
            condition:
              lambda: 'return id(menu_tracker).state == 1;'
            then:
              - homeassistant.service:
                  service: light.turn_on
                  data_template:
                    entity_id: light.${deviceParent}_lights
                    brightness: "{{ brightness | int }}"
                  variables:
                    brightness: !lambda 'return id(rotary_dial).state;'
              - sensor.template.publish:
                  id: brightness_percent
                  state: !lambda 'return (id(rotary_dial).state / 256) * 100;'
            else:
              - if:
                  condition:
                    lambda: 'return id(menu_tracker).state == 2;'
                  then:
                    - homeassistant.service:
                        service: light.turn_on
                        data_template:
                          entity_id: light.${deviceParent}_lights
                          color_temp: "{{ warmth | int }}"
                        variables:
                          warmth: !lambda 'return id(rotary_dial).state;'
                    - sensor.template.publish:
                        id: warmth_percent
                        state: !lambda 'return ((id(rotary_dial).state - 153) / (465 - 153)) * 100;'
                  else:
                    - if:
                        condition:
                          lambda: 'return id(menu_tracker).state == 0;'
                        then:
                          - display.page.show: pageBrightness
                          - sensor.template.publish:
                              id: brightness_percent
                              state: !lambda 'return (id(brightness).state / 256) * 100;'
                          - sensor.rotary_encoder.set_value:
                              id: rotary_dial
                              value: !lambda 'return id(brightness).state;'

  - platform: homeassistant
    id: brightness
    entity_id: sensor.${deviceParent}_brightness
    internal: true

  - platform: homeassistant
    id: warmth
    entity_id: sensor.${deviceParent}_warmth
    internal: true
    
  - platform: template
    name: "Menu Sensor"
    id: menu_tracker
    internal: true

  - platform: template
    id: brightness_percent
    lambda: |-
      if (id(brightness).state) {
        return (id(brightness).state / 256) * 100;
      } else {
        return 0;
      }
    update_interval: 60s
    internal: true
    
  - platform: template
    id: warmth_percent
    lambda: |-
      if (id(warmth).state) {
        return ((id(warmth).state - 153) / (465 - 153)) * 100;
      } else {
        return 0;
      }
    update_interval: 60s
    internal: true
    
binary_sensor:
  - platform: gpio
    pin:
      number: ${encoderSwitch}
      inverted: true
      mode: INPUT_PULLUP
    name: Switch ${deviceUpper}
    internal: true
    on_multi_click:
    - timing:
        - ON for at most 0.7s
        - OFF for at least 0.5s
      then:
        - logger.log: "Next Page"
        - display.page.show_next: i2cDisplay
        - delay: 0.8s
        - if:
            condition:
              lambda: 'return id(menu_tracker).state == 0;'
            then:
              - logger.log: "Switched to main page"
            else:
              - if:
                  condition:
                    lambda: 'return id(menu_tracker).state == 1;'
                  then:
                    - logger.log: "Switched to brightness page"
                    - sensor.rotary_encoder.set_value:
                        id: rotary_dial
                        value: !lambda 'return id(brightness).state;'
                  else:
                    - if:
                        condition:
                          lambda: 'return id(menu_tracker).state == 2;'
                        then:
                          - logger.log: "Switched to warmth page"
                          - sensor.rotary_encoder.set_value:
                              id: rotary_dial
                              value: !lambda 'return id(warmth).state;'