- id: update_climate_demo
  alias: Climate Update - Demo
  description: ''
  trigger:
  - entity_id: sensor.demo_climate_setpoint
    platform: state
  - entity_id: sensor.esp_uptime_plug_neopixel
    from: '0'
    platform: state
  - entity_id: sensor.esp_uptime_plug_screen
    from: '0'
    platform: state
  - entity_id: sensor.esp_uptime_counter_wedge_plus
    from: '0'
    platform: state
  condition: []
  action:
  - data_template:
      climate_setpoint: '{{ states(''sensor.demo_climate_setpoint'') | int }}'
    service: esphome.plug_screen_update_climate
  - data_template:
      climate_setpoint: '{{ states(''sensor.demo_climate_setpoint'') | int }}'
    service: esphome.plug_neopixel_update_climate
  - data_template:
      climate_setpoint: '{{ states(''sensor.demo_climate_setpoint'') | int }}'
    service: esphome.counter_wedge_plus_update_climate
